[IG]
ig = fsh-generated/resources/ImplementationGuide-elga.iv.diab.json
# change to
# ig = fsh-generated/resources/ImplementationGuide-hl7.at.fhir.elga.ips.diab.json
template = hl7.at.fhir.template#current