On this page you can find the mapping from the data model based on the "Rahmenkonzept Integrierte Versorgung Diabetes mellitus Typ 2" to the data model based on the [International Patient Summary (IPS)](https://build.fhir.org/ig/HL7/fhir-ips/).

Note, that only the relevant modules of the IPS will be included. Furthermore, even if not all modules of the IPS are mentioned in the mappings it is of course allowed to use them, if applicable.

<style type="text/css">
.grid .ips-recommended{background-color:#ffa52a;}
.grid .ips-header{background-color:#56c3f3;}
.grid .ips-required{background-color:#e53432;}
.grid .source-module{vertical-align:middle}
.grid .target-module{text-align:center;}
.grid .ips-optional{background-color:#91cf50;}
</style>

#### Types of Data

Please refer to [Types of Data for Diabetes](StructureDefinition-Datenarten-diab.html) for further details about this data model.

<table class="grid">
<tbody>
  <tr>
    <th class="source-module" colspan="2" rowspan="2">Diabetes<br> </th>
    <th class="target-module" colspan="6">IPS Modules</th>
  </tr>
  <tr>
    <th class="ips-required"><a href="StructureDefinition-MedicationSummary-ips.html"><strong>Medication Summary</strong></a></th>
    <th class="ips-required"><a href="StructureDefinition-AllergiesIntolerances-ips.html"><strong>Allergies and Intolerances</strong></a></th>
    <th class="ips-required"><a href="StructureDefinition-ProblemList-ips.html"><strong>Problem List</strong></a></th>
    <th class="ips-recommended"><a href="StructureDefinition-DiagnosticResults-ips.html"><strong>Diagnostic Results</strong></a></th>
    <th class="ips-optional"><a href="StructureDefinition-VitalSigns-ips.html"><strong>Vital Signs</strong></a></th>
    <th class="ips-optional"><a href="StructureDefinition-PlanOfCare-ips.html"><strong>Plan of Care</strong></a></th>
  </tr>
  <tr>
    <td rowspan="6">Essentielle Daten</td>
    <td>Diabetes- und Komplikations-Diagnosen</td>
    <td>-</td>
    <td>-</td>
    <td>.code</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <td>Kontakte &amp; Termine</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.activity</td>
  </tr>
  <tr>
    <td>Diabetesmedikation</td>
    <td>.medication[x]</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <td>Laborwerte (z.B. HbA1c)</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.code<br>.value[x]</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <td>Vitalparameter (Größe, Gewicht, BMI)</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.code<br>.value[x]</td>
    <td>-</td>
  </tr>
  <tr>
    <td>Metformin-Unverträglichkeit</td>
    <td>-</td>
    <td>.code</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <td rowspan="6">Sinnvolle zusätzliche Daten</td>
    <td>Nebendiagnosen</td>
    <td>-</td>
    <td>-</td>
    <td>.code</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <td>Gesamtmedikation</td>
    <td>.medication[x]</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <td>Laborwerte (z.B. HDL, LDL)</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.code<br>.value[x]</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <td>Vitalparameter (Blutdruck)</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.code<br>.value[x]</td>
    <td>-</td>
  </tr>
  <tr>
    <td>Medikamentenallergien</td>
    <td>-</td>
    <td>.code</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <td>Teilnahme am DMP</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.goal</td>
  </tr>
</tbody>
</table>

#### Types of Data

Please refer to [Datamodel Diabetes](StructureDefinition-Datamodel-diab.html) for further details about this data model.

<table class="grid">
<tbody>
  <tr>
    <th class="source-module" rowspan="2">Diabetes</th>
    <th class="target-module" colspan="12">IPS Modules</th>
    <th class="source-module" rowspan="2">Comment</th>
  </tr>
  <tr>
    <th><a href="StructureDefinition-Subject-ips.html"><strong>Subject</strong></a></th>
    <th class="ips-required"><a href="StructureDefinition-MedicationSummary-ips.html"><strong>Medication Summary</strong></a></th>
    <th class="ips-required"><a href="StructureDefinition-AllergiesIntolerances-ips.html"><strong>Allergies and Intolerances</strong></a></th>
    <th class="ips-required"><a href="StructureDefinition-ProblemList-ips.html"><strong>Problem List</strong></a></th>
    <th class="ips-recommended"><a href="StructureDefinition-MedicalDevices-ips.html"><strong>Medical Devices</strong></a></th>
    <th class="ips-recommended"><a href="StructureDefinition-DiagnosticResults-ips.html"><strong>Diagnostic Results</strong></a></th>
    <th class="ips-optional"><a href="StructureDefinition-VitalSigns-ips.html"><strong>Vital Signs</strong></a></th>
    <th class="ips-optional"><a href="StructureDefinition-HistoryOfIllnesses-ips.html"><strong>Past History of Illness</strong></a></th>
    <th class="ips-optional"><a href="StructureDefinition-SocialHistory-ips.html"><strong>Social History</strong></a></th>
    <th class="ips-optional"><a href="StructureDefinition-FunctionalStatus-ips.html"><strong>Functional Status</strong></a></th>
    <th class="ips-optional"><a href="StructureDefinition-PlanOfCare-ips.html"><strong>Plan of Care</strong></a></th>
    <th><a href="[StructureDefinition-PractitionerRole-ips.html](http://hl7.org/fhir/uv/ips/StructureDefinition/PractitionerRole-uv-ips)"><strong>PractitionerRole</strong></a></th>
  </tr>
  <tr>
    <td>Administrative Inhalte</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Untersuchung</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.activity</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;Untersuchungsdatum</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.activity.scheduled[x]</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;Art der Untersuchung</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.activity.code</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Patient</td>
    <td>n/a</td>
    <td>.subject</td>
    <td>.patient</td>
    <td>.subject</td>
    <td>.subject</td>
    <td>.subject</td>
    <td>.subject</td>
    <td>.subject</td>
    <td>.subject</td>
    <td>.subject</td>
    <td>.subject</td>
    <td>n/a</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;Geschlecht</td>
    <td>.gender</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;Familienname</td>
    <td>.name.family</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;Vorname</td>
    <td>.name.given</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;Geburtsdatum</td>
    <td>.birthDate</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;Adresse</td>
    <td>.address</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;SVNR</td>
    <td>.identifier</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;KV-Träger</td>
    <td>.contactInsurance</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Untersucher</td>
    <td>n/a</td>
    <td>.informationSource[x]</td>
    <td>.asserter[x]</td>
    <td>.asserter</td>
    <td>.source[x]</td>
    <td>.performer</td>
    <td>.performer</td>
    <td>.asserter</td>
    <td>.performer</td>
    <td>.assessor</td>
    <td>.activity.performer</td>
    <td>n/a</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;VPNR</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.practitioner.identifier</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;Fachgebiet</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.practitioner.qualification</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;Name</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.practitioner.name</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;Adresse</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.organization.address<br>.practitioner.address</td>
    <td></td>
  </tr>
  <tr>
    <td>Diagnosen</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Diabetesdiagnosen</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.code</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Komplikationsdiagnosen</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.code</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Nebendiagnosen</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.code</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Episoden von Gestationsdiabetes</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.code</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>Fußuntersuchung</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.code</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.activity.outcomeReference</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>Kontakte / Termine</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Schulungen</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.activity</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Fallkoordinator</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.author</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Fallführender Arzt</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.careTeam.participant.member</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Strukturierte (geplante) Terminisierung</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.activity</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>Therapie</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Individuelle Zielwerttabelle</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.activity.goal</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Ziele Lebensstil (Tabak, Bewegung, etc.)</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.activity.goal</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Diabetes- und Lipidmedikation</td>
    <td>-</td>
    <td>.medication[x]</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Gesamtmedikation</td>
    <td>-</td>
    <td>.medication[x]</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>Parameter</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Laborparameter</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.code and .value</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Verläufe</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.code and .valueSampledData</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Vitalparameter</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.code and .value</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>Allgemeine Informationen</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td>n/a</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;(Medikamenten-)Allergien</td>
    <td>-</td>
    <td>-</td>
    <td>.code</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;(Medikamenten-)Unverträglichkeiten</td>
    <td>-</td>
    <td>-</td>
    <td>.code</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Teilnahme an DMP</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.period</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Lebensqualität (EQ-5D-3L)</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.finding[x]</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Raucherstatus</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.valueCodeableConcept</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Alkoholkonsum</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.valueCodeableConcept</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Bewegung &amp; andere Lebensstilfaktoren</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.code and .value</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Selbstkontrolle</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>unclear</td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Dokumentierte Leistung</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>not permitted to be used</td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Verwendete Geräte</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>.device</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;Beilagen</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>unclear</td>
  </tr>
</tbody>
</table>